name: CustomF3Brand
version: '${project.version}'
main: it.multicoredev.cf3b.bukkit.CustomF3Brand
api-version: 1.13
author: LoreSchaeffer
description: Edit your server brand in debug screen
depend: [ 'ProtocolLib' ]
softdepend: [ 'PlaceholderAPI' ]

commands:
  f3reload:
    aliases: [ 'f3reload', 'f3r' ]
    description: Reload the config of the plugin